matches:
  # GUID
  - triggers: [":guid", ":uuid"]
    word: true
    replace: "{{output}}"
    vars:
      - name: output
        type: script
        params:
          args:
            - cargo
            - +nightly
            - --quiet
            - -Zscript
            - "%CONFIG%/scripts/guid.rs"

  # <br/>
  - trigger: <br>
    word: true
    replace: <br/>
    propagate_case: true

  # _=
  - trigger: "_= "
    replace: " = "
