matches:
  # GUID
  - triggers: ["%guid%", "%uuid%"]
    replace: "{{output}}"
    vars:
      - name: output
        type: script
        params:
          args:
            - cargo
            - +nightly
            - --quiet
            - -Zscript
            - "%CONFIG%/scripts/guid.rs"

