matches:
  # GUID
  - triggers: [";guid", ";uuid"]
    replace: "{{output}}"
    vars:
      - name: output
        type: script
        params:
          args:
            - cargo
            - +nightly
            - -Zscript
            - --quiet
            - "%CONFIG%/scripts/guid.rs"
